#!/bin/sh -
#
# Copyright (c) 2014, Quentin Schwerkolt
# All rights reserved.
#

PKGNAME="libiconv"
PKGVERSION="1.14"

. ../../common/pkgbld.subr

ARCHIVE="${PKGSRC}.tar.gz"
ARCHIVE_URL="http://ftp.gnu.org/gnu/${PKGNAME}"

prep() {
    :
}

build() {
    CONFIGURE="gnu"
    configure_args_add --enable-static
    configure_args_add --docdir=$DOCDIR

    configure
    make
}

package() {
    make install DESTDIR=$WRKDST
}

main $@
